### ISSUE TITLE
Support a wildcard in collections and permissions files

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-javaclient-util#107]
This is so that when using GenericFileLoader, collections/permissions can be applied on all files in a directory without naming each file

**Comment by rjrudin** [comment]
Updated docs - https://github.com/marklogic-community/ml-javaclient-util/wiki/Loading-files

**Comment by lifan0127** [comment]
@rjrudin Can I use the wildcard to include all files in sub-directories?

**Comment by rjrudin** [comment]
It's just for directory support so far. If you'd like to support sub-directories, please create a new ticket with a proposal for how to specify "all files in this directory and sub-directories" - it of course would need to be different from "*", which is for just the current directory.

**Comment by lifan0127** [comment]
Thanks for your prompt response! I have created a new issue here: https://github.com/marklogic-community/ml-javaclient-util/issues/120
