### ISSUE TITLE
JSON parse error crashes mlWatch task

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/ml-javaclient-util#122]
# Scenario
Given a JSON document with a syntax error in the mlModules path

When running `gradlew mlWatch -i`

Then gradle crashes with the following error:
```
> Local message: failed to apply resource at documents: Bad Request. Server Message: XDMP-JSONCHAR: xdmp:get-request-part-body("json") -- Unexpected character 'l' in JSON at line 344 char 2
```

# Expected behavior
`mlWatch` should report the error, but continue listening to file system changes after encountering the syntax error.  This provides the developer an opportunity to correct the syntax error and have it automatically retried without having to manually restart the `mlWatch` task.

The above error was captured while running `gradlew mlWatch -i`, which doesn't include the name of the file with a syntax issue.  Much like marklogic-community/ml-gradle#461 it would be nice if additional logging was provided to identify which JSON file has the parse error.

**Comment by rjrudin** [comment]
This will be a fix to DefaultModulesLoader so that if this line:

    List<DocumentFile> list = assetFileLoader.loadFiles(paths);

throws an error, it will be caught and logged if catchExceptions == true.
