### ISSUE TITLE
Set content format for documents written to MarkLogic

### ISSUE THREAD

**Issue by sastafford** [marklogic-community/ml-javaclient-util#50]
As a developer
I need to TITLE
So that the correct mime-type is set when POST documents to MarkLogic REST API. 

[TempRestBatchWriter](https://github.com/sastafford/marklogic-spring-batch/blob/master/infrastructure/src/main/java/com/marklogic/spring/batch/item/writer/support/TempRestBatchWriter.java)

[RestBatchWriter](https://github.com/rjrudin/ml-javaclient-util/blob/master/src/main/java/com/marklogic/client/batch/RestBatchWriter.java)

I need to call the DocumentManager.setContentFormat method offered in the ML Java Client 4.0 API.  Once you uptick this library to the latest Java Client API, I would like to get the RestBatchWriter to call this method.

**Comment by rjrudin** [comment]
I want to wait until 4.0 is available in the official place - http://developer.marklogic.com/maven2/com/marklogic/client-api-java/ . 

Until then, I think it's best to continue to subclass RestBatchWriter and provide a 4.0-specific implementation in a separate project that is able to depend on 4.0. I just don't want to make this project and ml-app-deployer and ml-gradle dependent on an EA version of something.

**Comment by rjrudin** [comment]
Tentatively planning on jumping from 2.x to 4.0.0 for this to match up with the Java Client API

**Comment by rjrudin** [comment]
@sastafford I'll soon make a 4.0 branch of this repo and publish a 4.0.alpha1 release that has this in it, along with a DMSDK impl of BatchWriter
