### ISSUE TITLE
Catch issues while loading REST API modules

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-javaclient-util#60]
DefaultModulesLoader doesn't have a way to listen for errors when loading REST API modules.

**Comment by rjrudin** [comment]
@paxtonhare I think we talked about this. When an error is caught, is the MarkLogicServerException sufficient to pass to the error listener, or do you need more information about what kind of module - i.e. options/services/transforms - was being loaded?

**Comment by rjrudin** [comment]
@paxtonhare Turns out there's a solution for this already with Spring's TaskExecutor, though it's a little awkward to setup. You can set a TaskDecorator on a ThreadPoolTaskExecutor. Let me know if this is suitable. 

    ThreadPoolTaskExecutor tpte = new ThreadPoolTaskExecutor();
    tpte.setAwaitTerminationSeconds(60 * 10);
    tpte.setWaitForTasksToCompleteOnShutdown(true);
    tpte.setCorePoolSize(16);
    tpte.setTaskDecorator(new TaskDecorator() {
      @Override
      public Runnable decorate(Runnable runnable) {
        return new Runnable() {
          @Override
          public void run() {
            System.out.println("IN TASK DECORATOR");
            try {
              runnable.run();
            } catch (Exception ex) {
              System.out.println("CAUGHT: " + ex.getMessage());
            }
          }
        };
      }
    });
    tpte.afterPropertiesSet();
    modulesLoader.setTaskExecutor(tpte);

**Comment by paxtonhare** [comment]
Sounds good enough. Thanks!

**Comment by paxtonhare** [comment]
@rjrudin feel free to close this bad boy. Your proposed solution worked for me.
