### ISSUE TITLE
InputStreams are not being closed in DefaultModulesLoader

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/ml-javaclient-util#82]
https://github.com/marklogic-community/ml-javaclient-util/blob/master/src/main/java/com/marklogic/client/ext/modulesloader/impl/DefaultModulesLoader.java#L384

There are several places where these InputStreams are not being closed in this file.

**Comment by rjrudin** [comment]
Publishing 3.2.0-82 as a short term fix for this.
