### ISSUE TITLE
Using special characters in username and password will break the xcc connection

### ISSUE THREAD

**Issue by peetkes** [marklogic-community/ml-javaclient-util#97]
When you use special characters like # or @ in your username and/or passwords the connection string for xcc will not work.
In the BasicConfig class the presence of those special characters will result in a new XccTemplate with a uri that will break.
Resolution would be to encode the username and the password before creating the xcc uri.

**Comment by rjrudin** [comment]
Thanks @peetkes - this was an issue with using the ContentSource constructor that uses a URI for connecting to ML. BasicConfig now uses the method in ContentSourceFactory where the host/port/username/password/database are passed in separately. 

I verified by changing my local admin password to "@admin#"; it failed with the current BasicConfig approach, and it works with the new approach. 

This will be in ml-gradle 3.7.2 which I'll get out shortly.
